### ISSUE TITLE
Can you make this work with shared libraries?

### ISSUE THREAD

**Issue by tshirtnjeans** [BeansIsFat/Compare-Plex-Libraries#1]
I'd like to compare my movie and/or TV show library with similar libraries on another server. This seems to only work with comparing libraries on my server. Would it be possible to add this improvement?

**Comment by BeansIsFat** [comment]
It depends on whether ExportTools can see the library. I don't have any shared libraries so I can't test this but you should be able to see a list of libraries in the ExportTools GUI. If the shared library is listed there, you should be able to use that name for `lib1` or `lib2`. If it's not listed, there's nothing I can do to add it.

**Comment by BeansIsFat** [comment]
I set up a second Plex server to see if ExportTools supported shared libraries and confirmed that it only works for local libraries. I'm not aware of any other tools that can export a shared library to a .csv file via CLI. If you find one, let me know and I'll look into it. But for now, this is not possible.
